import { trpc } from "@/lib/trpc";
import { CATEGORY_IDS, CATEGORY_THUMBNAILS, getCategory, type CategoryId } from "@shared/curriculumConfig";
import { getCategoryLevelsPath, getProfileIdFromSearch, getProfileLibraryPath } from "@shared/profileRoute";
import { ArrowLeft, ChevronRight, GripVertical, Palette, Play, Sparkles } from "lucide-react";
import { useLocation, useParams } from "wouter";

export default function Activities() {
  const { category: categoryParam } = useParams<{ category: string }>();
  const categoryId = CATEGORY_IDS.includes(categoryParam as CategoryId) ? categoryParam as CategoryId : CATEGORY_IDS[0];
  const category = getCategory(categoryId);
  const [, setLocation] = useLocation();
  const profileId = getProfileIdFromSearch(window.location.search);
  const snapshot = trpc.learning.childSnapshot.useQuery({ profileId }, { enabled: profileId > 0 });
  const currentLevel = snapshot.data?.progress.find((item) => item.subject === categoryId)?.unlockedLevel ?? 1;

  if (snapshot.isLoading) return <div className="kid-page grid min-h-screen place-items-center"><div className="h-12 w-12 animate-spin rounded-full border-4 border-[#e7ddff] border-t-[#6C4CE0]" /></div>;
  if (!snapshot.data) return <div className="kid-page grid min-h-screen place-items-center p-5"><div className="cloud-card rounded-[2rem] p-8 text-center"><p className="font-display text-2xl font-bold text-[#423a60]">Choose an explorer first</p><button onClick={() => setLocation("/profiles")} className="mt-5 rounded-2xl bg-[#6C4CE0] px-5 py-3 font-extrabold text-white">Back to profiles</button></div></div>;

  return <div className="kid-page min-h-screen pb-12"><header className="container flex items-center justify-between py-5"><button onClick={() => setLocation(getProfileLibraryPath(profileId))} className="lift-on-hover grid h-12 w-12 place-items-center rounded-2xl bg-white text-[#514471] shadow-sm" aria-label="Back to learning worlds"><ArrowLeft className="h-5 w-5" /></button><div className="text-center"><p className="font-display text-xl font-bold text-[#423a60]">{category.title}</p><p className="text-xs font-extrabold uppercase tracking-[.13em] text-[#8d84a4]">Six activities inside</p></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white shadow-sm"><Sparkles className="h-5 w-5" style={{ color: category.color }} /></span></header><main className="container max-w-5xl"><section className="relative overflow-hidden rounded-[2.5rem] bg-white shadow-[0_18px_45px_rgba(61,45,103,.1)]"><div className="grid md:grid-cols-[.9fr_1.1fr]"><img src={CATEGORY_THUMBNAILS[categoryId]} alt="" className="h-52 w-full object-cover md:h-full" /><div className="p-6 sm:p-8"><p className="text-sm font-black uppercase tracking-[.15em]" style={{ color: category.color }}>Choose an activity</p><h1 className="font-display mt-2 text-4xl font-bold tracking-[-.04em] text-[#423a60]">{category.title}</h1><p className="mt-3 font-bold leading-relaxed text-[#7b7494]">Pick one of the six activities below. Each activity uses the selected learner’s progress, age setting, stars, badges, and unlocked levels.</p><div className="mt-5 inline-flex rounded-full px-3 py-1.5 text-sm font-black" style={{ background: category.softColor, color: category.color }}>Level {currentLevel} is ready to play</div></div></div></section><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{category.activities.map((activity, index) => { const Icon = activity.interaction === "drawing" ? Palette : activity.interaction === "drag-and-drop" ? GripVertical : Play; return <button key={activity.id} onClick={() => setLocation(getCategoryLevelsPath(categoryId, profileId, activity.id))} className="lift-on-hover rounded-[1.7rem] bg-white p-5 text-left shadow-[0_10px_28px_rgba(64,47,110,.07)]"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl text-white" style={{ background: category.color }}><Icon className="h-5 w-5" /></span><span className="rounded-full bg-[#faf8ff] px-2.5 py-1 text-xs font-black text-[#8c83a4]">0{index + 1}</span></div><h2 className="font-display mt-6 text-2xl font-bold tracking-[-.03em] text-[#423a60]">{activity.title}</h2><p className="mt-2 min-h-10 text-sm font-bold leading-snug text-[#827b9e]">{activity.description}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-black" style={{ color: category.color }}>Open activity <ChevronRight className="h-4 w-4" /></span></button>; })}</section></main></div>;
}
